USE SUCOS;
DESCRIBE TB_CLIENTES;


-- ALTERAR ESTRUTURA NA BANCO DE DADOS
ALTER TABLE TB_CLIENTES ADD PRIMARY KEY (CPF);
ALTER TABLE TB_CLIENTES ADD COLUMN (DATA_NASCIMENTO DATE);
ALTER TABLE TB_CLIENTES MODIFY ESTADO VARCHAR(50);

-- DELETE
DELETE FROM TB_CLIENTES WHERE CPF = '00388934505';

-- RENOMEAR TABELA
RENAME TABLE TBCLIENTES TO TBCLIENTE;


-- INSERINDO DADOS NA TABELA
INSERT INTO TB_CLIENTES (
CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP, IDADE, SEXO, 
LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA, DATA_NASCIMENTO)
VALUES ('00388934505','João da Silva','Rua projetada A número 10','',
'VILA ROMAN', 'CARATINGA', 'AMAZONAS','2222222',30,'M', 10000.00, 2000,
0, '1989-10-05');

-- SELECT NA TABELA
SELECT * FROM TBCLIENTE;


-- MOSTRAR ESTRUTURA DA TABELA CLEINETES
DESCRIBE TB_CLIENTES;

-- TABELA EXCLUIDA E REFEITA QUERY AULA SQL_10 - DENTRO DA PASTA AULA05