-- CRIAÇÃO DE BANCO DE DADOS
CREATE DATABASE SUCOS;
USE SUCOS;
DESCRIBE TB_VENDEDORES;

-- CRIAÇÃO DE BANCO DE DADOS PELA ÁREA GRAFICA = BOTAÃO DIREITO EM CIMA DOS SCHEMA / CRIAR SCHEMA
CREATE SCHEMA `sucos2` DEFAULT CHARACTER SET utf8 ;

-- APAGAR BANCO DE DADOS
DROP DATABASE SUCOS;
-- APAGAR TABELA
DROP TABLE TABELA_DE_VENDEDORES;

-- CRIAR TABELA
CREATE TABLE TB_CLIENTES
( CPF VARCHAR (11) ,
NOME VARCHAR (100) ,
ENDERECO1 VARCHAR (150) ,
ENDERECO2 VARCHAR (150) ,
BAIRRO VARCHAR (50) ,
CIDADE VARCHAR (50) ,
ESTADO VARCHAR (2) ,
CEP VARCHAR (8) ,
IDADE SMALLINT,
SEXO VARCHAR (1) ,
LIMITE_CREDITO FLOAT ,
VOLUME_COMPRA FLOAT ,
PRIMEIRA_COMPRA BIT(1));


CREATE TABLE TB_VENDEDORES
( MATRICULA VARCHAR(5),
  NOME VARCHAR(100),
  COMISSAO FLOAT
);

-- INTERFACE GRAFICA
CREATE TABLE `sucos`.`tb_produto` (
  `PRODUTO` VARCHAR(20) NULL,
  `NOME` VARCHAR(150) NULL,
  `EMBALAGEM` VARCHAR(50) NULL,
  `TAMANHO` VARCHAR(50) NULL,
  `SABOR` VARCHAR(50) NULL,
  `PRECO_LISTA` FLOAT NULL);


-- INSERIR DADOS NA TABELA
INSERT INTO TB_PRODUTO ( PRODUTO,NOME,EMBALAGEM,TAMANHO,SABOR,PRECO_LISTA) 
VALUES 
('1040107', 'ligth-350ML-melancia', 'lata', '350ML', 'melancia', 4.56);

-- TABELA PRODUTOS
INSERT INTO TB_PRODUTO (PRODUTO,  NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) 
VALUES ('1037797', 'Clean - 2 Litros - Laranja','PET', '2 Litros', 'Laranja', 16.01);
INSERT INTO TB_PRODUTO (PRODUTO,  NOME, EMBALAGEM, TAMANHO, SABOR,PRECO_LISTA) 
VALUES ('1000889', 'Sabor da Montanha - 700 ml - Uva','Garrafa', '700 ml', 'Uva', 6.31);
INSERT INTO TB_PRODUTO (PRODUTO,  NOME, EMBALAGEM, TAMANHO, SABOR,PRECO_LISTA) 
VALUES ('1004327', 'Videira do Campo - 1,5 Litros - Melância','PET', '1,5 Litros', 'Melância', 19.51);
INSERT INTO TB_PRODUTO (PRODUTO,  NOME, EMBALAGEM, TAMANHO, SABOR,PRECO_LISTA)
VALUES ('1078680', 'Frescor do Verão - 470 ml - Manga', 'Lata', '470 ml','Manga',5.18);

-- TABELA VENDEDORES
INSERT INTO TB_VENDEDORES (MATRICULA, NOME, COMISSAO, DATA_ADMISSAO, FERIAS) VALUES ('00233', 'GUSTAVO SILVA', 10, '2021/01/04', 'nao');
INSERT INTO TB_VENDEDORES (MATRICULA, NOME, COMISSAO, DATA_ADMISSAO, FERIAS)
VALUES ('00240', 'Kessilin Lima', 7,'2022/06/11', 'nao');
INSERT INTO TB_VENDEDORES (MATRICULA, NOME, COMISSAO, DATA_ADMISSAO, FERIAS)
VALUES ('00250', 'Cláudia Morais', 8,'2019/10/05', 'sim');


-- ALTERAR REGISTROS NA TABELA
UPDATE TB_PRODUTO SET EMBALAGEM = 'Garrafa' WHERE PRODUTO = '1078680';
UPDATE TB_VENDEDORES SET COMISSAO = 11 WHERE MATRICULA = '00236';
UPDATE TB_VENDEDORES SET NOME = 'José Geraldo da Fonseca Junior' WHERE MATRICULA = '00233';
UPDATE TB_VENDEDORES SET DATA_ADMISSAO = '2010/01/04', FERIAS = 'sim' WHERE MATRICULA = '00235';

-- DELETAR REGISTROS DA TABELA
DELETE FROM TB_PRODUTO WHERE PRODUTO = '1078680';
DELETE FROM TB_VENDEDORES WHERE MATRICULA = '00233';

-- ALTERAR ESTRUTURA DO BANCO DE DADOS
ALTER TABLE TB_PRODUTO ADD PRIMARY KEY (PRODUTO);
ALTER TABLE TB_VENDEDORES ADD PRIMARY KEY (MATRICULA);
ALTER TABLE TB_VENDEDORES ADD COLUMN (DATA_ADMISSAO DATE, FERIAS VARCHAR(50));

-- RENOMEAR TABELA
RENAME TABLE TB_PRODUTO TO TBPRODUTO;

-- SELECT NAS TABELAS
SELECT * FROM TB_VENDEDORES;
SELECT * FROM TB_VENDEDORES WHERE MATRICULA='00235';
SELECT * FROM TB_VENDEDORES WHERE COMISSAO > 9;
SELECT * FROM TBPRODUTO;
SELECT * FROM TB_VENDEDORES WHERE YEAR(DATA_ADMISSAO) <= 2016 AND FERIAS = 'SIM';

-- TABELA EXCLUIDA E REFEITA QUERY AULA SQL_10 - DENTRO DA PASTA AULA05