-- TODOS OS CAMPOS
SELECT * FROM TBCLIENTE;
SELECT * FROM TBPRODUTO;

-- SELECIONAR APENAS ALGUNS CAMPOS
SELECT CPF, NOME FROM TBCLIENTE;

-- SELECIONAR ALGUNS CAMPOS E TRAZER UM NUMERO ESPECIFICO  
SELECT CPF, NOME FROM TBCLIENTE LIMIT 5;

-- DAR APELIDO PARA OS CAMPOS
SELECT CPF AS CPF_CLINETE, NOME AS NOME_CLIENTE FROM TBCLIENTE;

-- SELECT COM WHERE
SELECT * FROM TBPRODUTO WHERE SABOR = 'citricos';

-- DESABILITAR SAFE MODE
SET SQL_SAFE_UPDATES=0;

-- UPDATE
UPDATE TBPRODUTO SET SABOR = 'CITRICOS' WHERE SABOR = 'limão';

-- SELECT COM OPERAÇÕES LÓGICAS
SELECT NOME, IDADE, ESTADO, DATA_NASCIMENTO FROM TBCLIENTE WHERE IDADE <= 22;
SELECT NOME, IDADE, ESTADO FROM TBCLIENTE WHERE ESTADO <> 'SP' AND IDADE >= 22 ;

-- SELECT EM VALORES DE PONTO FLUTUANTE
SELECT * FROM TBPRODUTO WHERE PRECO_LISTA BETWEEN 16.007 AND 16.009;

-- SELECT DATA
SELECT * FROM TBCLIENTE WHERE DATA_NASCIMENTO > '2000-01-01';
SELECT * FROM TBCLIENTE WHERE YEAR(DATA_NASCIMENTO) < 2000;
SELECT * FROM TBCLIENTE WHERE MONTH(DATA_NASCIMENTO) = 9;


-- SELECT COMPOSTO
SELECT NOME, IDADE, ESTADO, DATA_NASCIMENTO FROM TBCLIENTE WHERE IDADE >= 18 AND IDADE <=23 AND SEXO = 'm';
SELECT NOME, IDADE, ESTADO, DATA_NASCIMENTO FROM TBCLIENTE WHERE IDADE BETWEEN 18 AND 23;