SELECT * FROM tbproduto;
SELECT * FROM TBCLIENTE;

SELECT * FROM tbproduto WHERE SABOR = 'Manga'
OR TAMANHO = '470 ml';

SELECT * FROM tbproduto WHERE SABOR = 'Manga'
AND TAMANHO = '470 ml';

SELECT * FROM tbproduto WHERE NOT (SABOR = 'Manga'
AND TAMANHO = '470 ml');

SELECT * FROM tbproduto WHERE NOT (SABOR = 'Manga'
OR TAMANHO = '470 ml');

SELECT * FROM tbproduto WHERE SABOR = 'Manga'
AND NOT ( TAMANHO = '470 ml');

SELECT * FROM tbproduto WHERE SABOR IN ('Laranja', 'Manga');

SELECT * FROM tbproduto WHERE SABOR = 'Laranja' OR SABOR = 'Manga';

SELECT * FROM tbproduto WHERE CIDADE IN ('Rio de Janeiro','São Paulo')
AND IDADE >= 20;

SELECT * FROM tbproduto WHERE CIDADE IN ('Rio de Janeiro','São Paulo')
AND (IDADE >= 20 AND IDADE <= 22);


-- COMANDO LIKE
-- COMEÇA
SELECT * FROM TBPRODUTO WHERE SABOR LIKE 'maça%';
-- TERMINA
SELECT * FROM TBPRODUTO WHERE SABOR LIKE '%maça';
SELECT * FROM TBCLIENTE WHERE NOME LIKE '%MATTOS';
-- CONTÉM
SELECT * FROM TBPRODUTO WHERE SABOR LIKE '%maça%' AND EMBALAGEM = 'PET' AND TAMANHO > '1 LITRO';

-- COMANDO DISTINCT
SELECT DISTINCT EMBALAGEM, TAMANHO FROM TBPRODUTO WHERE SABOR = 'LARANJA';
SELECT DISTINCT BAIRRO FROM TBCLIENTE WHERE CIDADE = 'RIO DE JANEIRO';