
SELECT * FROM tbproduto;

SELECT * FROM tbproduto ORDER BY PRECO_LISTA;

SELECT * FROM tbproduto ORDER BY PRECO_LISTA DESC;

SELECT * FROM tbproduto ORDER BY NOME;

SELECT * FROM tbproduto ORDER BY NOME DESC;

SELECT * FROM tbproduto ORDER BY EMBALAGEM DESC, NOME ASC;
