
SELECT * FROM tbcliente;

SELECT * FROM TABELA_DE_CLIENTES WHERE ESTADO = 'SP';

SELECT ESTADO, MAX(VOLUME_DE_COMPRA) AS VOLUME FROM TABELA_DE_CLIENTES GROUP BY ESTADO
UNION
SELECT ESTADO, MIN(VOLUME_DE_COMPRA) AS VOLUME FROM TABELA_DE_CLIENTES GROUP BY ESTADO ORDER BY ESTADO;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS LIMITE_TOTAL FROM TABELA_DE_CLIENTES WHERE ESTADO  = 'SP' GROUP BY ESTADO;

SELECT EMBALAGEM, PRECO_LISTA FROM tbproduto;

SELECT EMBALAGEM, MAX(PRECO_LISTA) AS MAIOR_PRECO FROM tbProduto GROUP BY EMBALAGEM;

SELECT EMBALAGEM, COUNT(*) AS CONTADOR FROM TABELA_DE_produtoS GROUP BY EMBALAGEM;

SELECT COUNT(*) AS CONTADOR FROM TABELA_DE_produtoS;

SELECT BAIRRO, SUM(LIMITE_CREDITO) AS LIMITE FROM tbcliente GROUP BY BAIRRO;

SELECT BAIRRO, SUM(LIMITE_CREDITO) AS LIMITE FROM tbcliente
WHERE CIDADE = 'Rio de Janeiro' GROUP BY BAIRRO;

SELECT ESTADO, BAIRRO, SUM(LIMITE_CREDITO) AS LIMITE FROM tbcliente
GROUP BY ESTADO, BAIRRO;

SELECT ESTADO, BAIRRO, SUM(LIMITE_CREDITO) AS LIMITE FROM tbcliente
WHERE CIDADE = 'Rio de Janeiro' GROUP BY ESTADO, BAIRRO;

SELECT ESTADO, BAIRRO, SUM(LIMITE_CREDITO) AS LIMITE FROM tbcliente 
WHERE CIDADE = 'Rio de Janeiro' 
GROUP BY ESTADO, BAIRRO
ORDER BY BAIRRO;

