USE SUCOS;
SELECT * FROM tBproduto;
SELECT * FROM tBCLIENTE;


SELECT NOME, DATA_NASCIMENTO,
CASE 
	WHEN YEAR(DATA_NASCIMENTO) > '1995' THEN 'CRIANÇA'
    WHEN YEAR(DATA_NASCIMENTO) > '1990' AND  YEAR(DATA_NASCIMENTO) <= '1995' THEN 'JOVEN'
    ELSE 'VELHO'
END AS 'GERAÇÃO'
FROM TBCLIENTE ORDER BY DATA_NASCIMENTO, NOME;



SELECT NOME, PRECO_LISTA,
CASE 
   WHEN PRECO_LISTA >= 12 THEN 'PRODUTO CARO'
   WHEN PRECO_LISTA >= 7 AND PRECO_LISTA < 12 THEN 'PRODUTO EM CONTA'
   ELSE 'PRODUTO BARATO' 
END AS STATUS_PRECO 
FROM TBproduto ORDER BY STATUS_PRECO, NOME;

SELECT EMBALAGEM,
CASE 
   WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
   WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
   ELSE 'PRODUTO BARATO' 
END AS STATUS_PRECO, AVG(PRECO_DE_LISTA) AS PRECO_MEDIO
FROM tabela_de_produtos
WHERE sabor = 'Manga'
GROUP BY EMBALAGEM, 
CASE 
   WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
   WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
   ELSE 'PRODUTO BARATO' 
END AS STATUS_PRECO, AVG(PRECO_DE_LISTA) AS PRECO_MEDIO;


SELECT * FROM TBCLIENTE;
