use vendas_sucos;
SELECT * FROM SUCOS_VENDAS.TABELA_DE_PRODUTOS;
SELECT * FROM SUCOS_VENDAS.TABELA_DE_PRODUTOS WHERE CODIGO_DO_PRODUTO NOT IN (SELECT CODIGO FROM PRODUTOS);

-- iNSERIR REGISTROS DE OUTRA TABELA
INSERT INTO produtos
SELECT CODIGO_DO_PRODUTO AS CODIGO, NOME_DO_PRODUTO AS DESCRITOR,
SABOR, TAMANHO, EMBALAGEM,  PRECO_DE_LISTA AS PRECO_LISTA
FROM sucos_vendas.tabela_de_produtos
WHERE CODIGO_DO_PRODUTO NOT IN (SELECT CODIGO FROM produtos);

INSERT INTO clientes
(CPF,NOME,ENDERECO,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA)
SELECT CPF, NOME, ENDERECO_1 AS ENDERECO, BAIRRO, CIDADE, ESTADO, CEP,DATA_DE_NASCIMENTO 
AS DATA_NASCIMENTO, IDADE, SEXO,LIMITE_DE_CREDITO 
AS LIMITE_CREDITO, VOLUME_DE_COMPRA 
AS VOLUME_COMPRA,PRIMEIRA_COMPRA 
FROM sucos_vendas.tabela_de_clientes 
WHERE CPF NOT IN (SELECT CPF FROM clientes);

SELECT * FROM VENDEDORES;
SET sql_safe_updates=0;
UPDATE VENDEDORES SET NOME = "Márcio almeida Silva" WHERE MATRICULA = 235; 
UPDATE VENDEDORES SET NOME = "Péricles Alves" WHERE MATRICULA = 238; 
UPDATE VENDEDORES SET NOME = "Cláudia Morais" WHERE MATRICULA = 236; 

SELECT * FROM PRODUTOS;
SELECT * FROM PRODUTOS WHERE SABOR LIKE "AÇAI%";
UPDATE PRODUTOS SET SABOR = "Açai do Para" WHERE SABOR = "AÇAI";
UPDATE CLIENTES SET ENDERECO = 'R. Jorge Emilio 23',
BAIRRO = 'Santo Amaro', CIDADE = 'São Paulo', ESTADO = 'SP', CEP = '8833223'
WHERE CPF = '19290992743 ';

-- UPDATE USANDO CAMPOS DE OUTRA TABELA
SELECT * FROM VENDEDORES;
SELECT * FROM SUCOS_VENDAS.TABELA_DE_VENDEDORES;
SELECT * FROM VENDEDORES A 
INNER JOIN SUCOS_VENDAS.TABELA_DE_VENDEDORES B 
ON  A.MATRICULA = SUBSTRING(B.MATRICULA,3,3);
UPDATE VENDEDORES A INNER JOIN SUCOS_VENDAS.TABELA_DE_VENDEDORES B 
ON  A.MATRICULA = SUBSTRING(B.MATRICULA,3,3)
SET A.FERIAS = B.DE_FERIAS;

SELECT A.CPF FROM CLIENTES A
INNER JOIN VENDEDORES B
ON A.BAIRRO = B.BAIRRO;
UPDATE CLIENTES A INNER JOIN VENDEDORES B
ON A.BAIRRO = B.BAIRRO
SET A.VOLUME_COMPRA = A.VOLUME_COMPRA * 1.30;

-- DELETE
SELECT A.NUMERO FROM NOTAS A
INNER JOIN CLIENTES B ON A.CPF = B.CPF
WHERE B.IDADE <= 18;

DELETE A FROM NOTAS A
INNER JOIN CLIENTES B ON A.CPF = B.CPF
WHERE B.IDADE <= 18;

-- NÃO COMPILA O CODIGO 
START TRANSACTION;
SELECT * FROM CLIENTES;
UPDATE CLIENTES SET IDADE = 1;
ROLLBACK;
-- COMMIT